name: Build and Deploy Grocery Bot

on:
  push:
    branches:
      - main  # Triggers only on pushes to 'main'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Verify Docker setup
        run: |
          docker --version
          docker compose version

      - name: Make build script executable
        run: chmod +x scripts/build.sh

      - name: Create .env file from secrets
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "AUTHORIZED_USERS=${{ secrets.AUTHORIZED_USERS }}" >> .env
          echo "STATUS_REPORTING_ENABLED=false" >> .env

      - name: Run build and deployment script
        run: ./scripts/build.sh

      - name: Verify deployment
        run: |
          echo "Waiting for services to be ready..."
          sleep 10
          docker compose ps
          docker compose logs --tail=10 grocery-bot
